name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: conftest --version

      - name: Install bats
        run: |
          sudo apt-get install bats
          bats --version
      - name: Test plugin with bats
        run: |
          bats test
